//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace SeppukuMap.SeppukuService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://seppuku.pl/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int UserIdField;
        
        private bool IsApprovedField;
        
        private string UserNameField;
        
        private string EmailField;
        
        private System.DateTime CreateDateField;
        
        private string PasswordHashField;
        
        private System.Guid AuthorizatonKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool IsApproved {
            get {
                return this.IsApprovedField;
            }
            set {
                if ((this.IsApprovedField.Equals(value) != true)) {
                    this.IsApprovedField = value;
                    this.RaisePropertyChanged("IsApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Guid AuthorizatonKey {
            get {
                return this.AuthorizatonKeyField;
            }
            set {
                if ((this.AuthorizatonKeyField.Equals(value) != true)) {
                    this.AuthorizatonKeyField = value;
                    this.RaisePropertyChanged("AuthorizatonKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://seppuku.pl/")]
    public partial class OrderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderTypeField;
        
        private int sourceTileIdField;
        
        private int destinationTileIdField;
        
        private int unitCountField;
        
        private int orderCostField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string orderType {
            get {
                return this.orderTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.orderTypeField, value) != true)) {
                    this.orderTypeField = value;
                    this.RaisePropertyChanged("orderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sourceTileId {
            get {
                return this.sourceTileIdField;
            }
            set {
                if ((this.sourceTileIdField.Equals(value) != true)) {
                    this.sourceTileIdField = value;
                    this.RaisePropertyChanged("sourceTileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int destinationTileId {
            get {
                return this.destinationTileIdField;
            }
            set {
                if ((this.destinationTileIdField.Equals(value) != true)) {
                    this.destinationTileIdField = value;
                    this.RaisePropertyChanged("destinationTileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int unitCount {
            get {
                return this.unitCountField;
            }
            set {
                if ((this.unitCountField.Equals(value) != true)) {
                    this.unitCountField = value;
                    this.RaisePropertyChanged("unitCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int orderCost {
            get {
                return this.orderCostField;
            }
            set {
                if ((this.orderCostField.Equals(value) != true)) {
                    this.orderCostField = value;
                    this.RaisePropertyChanged("orderCost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapModel", Namespace="http://seppuku.pl/")]
    public partial class MapModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.TileInfo> tilesField;
        
        private System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.Owner> playersField;
        
        private System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.OrderInfo> ordersField;
        
        private int riceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.TileInfo> tiles {
            get {
                return this.tilesField;
            }
            set {
                if ((object.ReferenceEquals(this.tilesField, value) != true)) {
                    this.tilesField = value;
                    this.RaisePropertyChanged("tiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.Owner> players {
            get {
                return this.playersField;
            }
            set {
                if ((object.ReferenceEquals(this.playersField, value) != true)) {
                    this.playersField = value;
                    this.RaisePropertyChanged("players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.OrderInfo> orders {
            get {
                return this.ordersField;
            }
            set {
                if ((object.ReferenceEquals(this.ordersField, value) != true)) {
                    this.ordersField = value;
                    this.RaisePropertyChanged("orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int rice {
            get {
                return this.riceField;
            }
            set {
                if ((this.riceField.Equals(value) != true)) {
                    this.riceField = value;
                    this.RaisePropertyChanged("rice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TileInfo", Namespace="http://seppuku.pl/")]
    public partial class TileInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tileIdField;
        
        private int xField;
        
        private int yField;
        
        private string nameField;
        
        private System.Nullable<int> ownerIdField;
        
        private int numberOfWorkersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tileId {
            get {
                return this.tileIdField;
            }
            set {
                if ((this.tileIdField.Equals(value) != true)) {
                    this.tileIdField = value;
                    this.RaisePropertyChanged("tileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> ownerId {
            get {
                return this.ownerIdField;
            }
            set {
                if ((this.ownerIdField.Equals(value) != true)) {
                    this.ownerIdField = value;
                    this.RaisePropertyChanged("ownerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int numberOfWorkers {
            get {
                return this.numberOfWorkersField;
            }
            set {
                if ((this.numberOfWorkersField.Equals(value) != true)) {
                    this.numberOfWorkersField = value;
                    this.RaisePropertyChanged("numberOfWorkers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Owner", Namespace="http://seppuku.pl/")]
    public partial class Owner : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int playerIdField;
        
        private string playerNameField;
        
        private string playerColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int playerId {
            get {
                return this.playerIdField;
            }
            set {
                if ((this.playerIdField.Equals(value) != true)) {
                    this.playerIdField = value;
                    this.RaisePropertyChanged("playerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string playerName {
            get {
                return this.playerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.playerNameField, value) != true)) {
                    this.playerNameField = value;
                    this.RaisePropertyChanged("playerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string playerColor {
            get {
                return this.playerColorField;
            }
            set {
                if ((object.ReferenceEquals(this.playerColorField, value) != true)) {
                    this.playerColorField = value;
                    this.RaisePropertyChanged("playerColor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://seppuku.pl/", ConfigurationName="SeppukuService.SeppukuServiceSoap")]
    public interface SeppukuServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://seppuku.pl/GetUsers", ReplyAction="*")]
        System.IAsyncResult BeginGetUsers(SeppukuMap.SeppukuService.GetUsersRequest request, System.AsyncCallback callback, object asyncState);
        
        SeppukuMap.SeppukuService.GetUsersResponse EndGetUsers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://seppuku.pl/UpdateGameState", ReplyAction="*")]
        System.IAsyncResult BeginUpdateGameState(SeppukuMap.SeppukuService.UpdateGameStateRequest request, System.AsyncCallback callback, object asyncState);
        
        SeppukuMap.SeppukuService.UpdateGameStateResponse EndUpdateGameState(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://seppuku.pl/addOrder", ReplyAction="*")]
        System.IAsyncResult BeginaddOrder(SeppukuMap.SeppukuService.addOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        SeppukuMap.SeppukuService.addOrderResponse EndaddOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://seppuku.pl/removeOrder", ReplyAction="*")]
        System.IAsyncResult BeginremoveOrder(SeppukuMap.SeppukuService.removeOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        SeppukuMap.SeppukuService.removeOrderResponse EndremoveOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://seppuku.pl/GetMapModel", ReplyAction="*")]
        System.IAsyncResult BeginGetMapModel(SeppukuMap.SeppukuService.GetMapModelRequest request, System.AsyncCallback callback, object asyncState);
        
        SeppukuMap.SeppukuService.GetMapModelResponse EndGetMapModel(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(SeppukuMap.SeppukuService.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(SeppukuMap.SeppukuService.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://seppuku.pl/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.User> GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.User> GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateGameStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateGameState", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.UpdateGameStateRequestBody Body;
        
        public UpdateGameStateRequest() {
        }
        
        public UpdateGameStateRequest(SeppukuMap.SeppukuService.UpdateGameStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateGameStateRequestBody {
        
        public UpdateGameStateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateGameStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateGameStateResponse", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.UpdateGameStateResponseBody Body;
        
        public UpdateGameStateResponse() {
        }
        
        public UpdateGameStateResponse(SeppukuMap.SeppukuService.UpdateGameStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://seppuku.pl/")]
    public partial class UpdateGameStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateGameStateResult;
        
        public UpdateGameStateResponseBody() {
        }
        
        public UpdateGameStateResponseBody(string UpdateGameStateResult) {
            this.UpdateGameStateResult = UpdateGameStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrder", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.addOrderRequestBody Body;
        
        public addOrderRequest() {
        }
        
        public addOrderRequest(SeppukuMap.SeppukuService.addOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://seppuku.pl/")]
    public partial class addOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SeppukuMap.SeppukuService.OrderInfo orderInfo;
        
        public addOrderRequestBody() {
        }
        
        public addOrderRequestBody(SeppukuMap.SeppukuService.OrderInfo orderInfo) {
            this.orderInfo = orderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrderResponse", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.addOrderResponseBody Body;
        
        public addOrderResponse() {
        }
        
        public addOrderResponse(SeppukuMap.SeppukuService.addOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addOrderResponseBody {
        
        public addOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeOrder", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.removeOrderRequestBody Body;
        
        public removeOrderRequest() {
        }
        
        public removeOrderRequest(SeppukuMap.SeppukuService.removeOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://seppuku.pl/")]
    public partial class removeOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SeppukuMap.SeppukuService.OrderInfo orderInfo;
        
        public removeOrderRequestBody() {
        }
        
        public removeOrderRequestBody(SeppukuMap.SeppukuService.OrderInfo orderInfo) {
            this.orderInfo = orderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeOrderResponse", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.removeOrderResponseBody Body;
        
        public removeOrderResponse() {
        }
        
        public removeOrderResponse(SeppukuMap.SeppukuService.removeOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class removeOrderResponseBody {
        
        public removeOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMapModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMapModel", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.GetMapModelRequestBody Body;
        
        public GetMapModelRequest() {
        }
        
        public GetMapModelRequest(SeppukuMap.SeppukuService.GetMapModelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMapModelRequestBody {
        
        public GetMapModelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMapModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMapModelResponse", Namespace="http://seppuku.pl/", Order=0)]
        public SeppukuMap.SeppukuService.GetMapModelResponseBody Body;
        
        public GetMapModelResponse() {
        }
        
        public GetMapModelResponse(SeppukuMap.SeppukuService.GetMapModelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://seppuku.pl/")]
    public partial class GetMapModelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SeppukuMap.SeppukuService.MapModel GetMapModelResult;
        
        public GetMapModelResponseBody() {
        }
        
        public GetMapModelResponseBody(SeppukuMap.SeppukuService.MapModel GetMapModelResult) {
            this.GetMapModelResult = GetMapModelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SeppukuServiceSoapChannel : SeppukuMap.SeppukuService.SeppukuServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.User> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.User>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UpdateGameStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateGameStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetMapModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMapModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SeppukuMap.SeppukuService.MapModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SeppukuMap.SeppukuService.MapModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SeppukuServiceSoapClient : System.ServiceModel.ClientBase<SeppukuMap.SeppukuService.SeppukuServiceSoap>, SeppukuMap.SeppukuService.SeppukuServiceSoap {
        
        private BeginOperationDelegate onBeginGetUsersDelegate;
        
        private EndOperationDelegate onEndGetUsersDelegate;
        
        private System.Threading.SendOrPostCallback onGetUsersCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateGameStateDelegate;
        
        private EndOperationDelegate onEndUpdateGameStateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateGameStateCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddOrderDelegate;
        
        private EndOperationDelegate onEndaddOrderDelegate;
        
        private System.Threading.SendOrPostCallback onaddOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginremoveOrderDelegate;
        
        private EndOperationDelegate onEndremoveOrderDelegate;
        
        private System.Threading.SendOrPostCallback onremoveOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMapModelDelegate;
        
        private EndOperationDelegate onEndGetMapModelDelegate;
        
        private System.Threading.SendOrPostCallback onGetMapModelCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SeppukuServiceSoapClient() {
        }
        
        public SeppukuServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeppukuServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeppukuServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeppukuServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetUsersCompletedEventArgs> GetUsersCompleted;
        
        public event System.EventHandler<UpdateGameStateCompletedEventArgs> UpdateGameStateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> addOrderCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> removeOrderCompleted;
        
        public event System.EventHandler<GetMapModelCompletedEventArgs> GetMapModelCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SeppukuMap.SeppukuService.SeppukuServiceSoap.BeginGetUsers(SeppukuMap.SeppukuService.GetUsersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUsers(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetUsers(System.AsyncCallback callback, object asyncState) {
            SeppukuMap.SeppukuService.GetUsersRequest inValue = new SeppukuMap.SeppukuService.GetUsersRequest();
            inValue.Body = new SeppukuMap.SeppukuService.GetUsersRequestBody();
            return ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).BeginGetUsers(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeppukuMap.SeppukuService.GetUsersResponse SeppukuMap.SeppukuService.SeppukuServiceSoap.EndGetUsers(System.IAsyncResult result) {
            return base.Channel.EndGetUsers(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.User> EndGetUsers(System.IAsyncResult result) {
            SeppukuMap.SeppukuService.GetUsersResponse retVal = ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).EndGetUsers(result);
            return retVal.Body.GetUsersResult;
        }
        
        private System.IAsyncResult OnBeginGetUsers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetUsers(callback, asyncState);
        }
        
        private object[] OnEndGetUsers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SeppukuMap.SeppukuService.User> retVal = this.EndGetUsers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUsersCompleted(object state) {
            if ((this.GetUsersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUsersAsync() {
            this.GetUsersAsync(null);
        }
        
        public void GetUsersAsync(object userState) {
            if ((this.onBeginGetUsersDelegate == null)) {
                this.onBeginGetUsersDelegate = new BeginOperationDelegate(this.OnBeginGetUsers);
            }
            if ((this.onEndGetUsersDelegate == null)) {
                this.onEndGetUsersDelegate = new EndOperationDelegate(this.OnEndGetUsers);
            }
            if ((this.onGetUsersCompletedDelegate == null)) {
                this.onGetUsersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUsersCompleted);
            }
            base.InvokeAsync(this.onBeginGetUsersDelegate, null, this.onEndGetUsersDelegate, this.onGetUsersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SeppukuMap.SeppukuService.SeppukuServiceSoap.BeginUpdateGameState(SeppukuMap.SeppukuService.UpdateGameStateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateGameState(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUpdateGameState(System.AsyncCallback callback, object asyncState) {
            SeppukuMap.SeppukuService.UpdateGameStateRequest inValue = new SeppukuMap.SeppukuService.UpdateGameStateRequest();
            inValue.Body = new SeppukuMap.SeppukuService.UpdateGameStateRequestBody();
            return ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).BeginUpdateGameState(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeppukuMap.SeppukuService.UpdateGameStateResponse SeppukuMap.SeppukuService.SeppukuServiceSoap.EndUpdateGameState(System.IAsyncResult result) {
            return base.Channel.EndUpdateGameState(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndUpdateGameState(System.IAsyncResult result) {
            SeppukuMap.SeppukuService.UpdateGameStateResponse retVal = ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).EndUpdateGameState(result);
            return retVal.Body.UpdateGameStateResult;
        }
        
        private System.IAsyncResult OnBeginUpdateGameState(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginUpdateGameState(callback, asyncState);
        }
        
        private object[] OnEndUpdateGameState(System.IAsyncResult result) {
            string retVal = this.EndUpdateGameState(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateGameStateCompleted(object state) {
            if ((this.UpdateGameStateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateGameStateCompleted(this, new UpdateGameStateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateGameStateAsync() {
            this.UpdateGameStateAsync(null);
        }
        
        public void UpdateGameStateAsync(object userState) {
            if ((this.onBeginUpdateGameStateDelegate == null)) {
                this.onBeginUpdateGameStateDelegate = new BeginOperationDelegate(this.OnBeginUpdateGameState);
            }
            if ((this.onEndUpdateGameStateDelegate == null)) {
                this.onEndUpdateGameStateDelegate = new EndOperationDelegate(this.OnEndUpdateGameState);
            }
            if ((this.onUpdateGameStateCompletedDelegate == null)) {
                this.onUpdateGameStateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateGameStateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateGameStateDelegate, null, this.onEndUpdateGameStateDelegate, this.onUpdateGameStateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SeppukuMap.SeppukuService.SeppukuServiceSoap.BeginaddOrder(SeppukuMap.SeppukuService.addOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginaddOrder(SeppukuMap.SeppukuService.OrderInfo orderInfo, System.AsyncCallback callback, object asyncState) {
            SeppukuMap.SeppukuService.addOrderRequest inValue = new SeppukuMap.SeppukuService.addOrderRequest();
            inValue.Body = new SeppukuMap.SeppukuService.addOrderRequestBody();
            inValue.Body.orderInfo = orderInfo;
            return ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).BeginaddOrder(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeppukuMap.SeppukuService.addOrderResponse SeppukuMap.SeppukuService.SeppukuServiceSoap.EndaddOrder(System.IAsyncResult result) {
            return base.Channel.EndaddOrder(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndaddOrder(System.IAsyncResult result) {
            SeppukuMap.SeppukuService.addOrderResponse retVal = ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).EndaddOrder(result);
        }
        
        private System.IAsyncResult OnBeginaddOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SeppukuMap.SeppukuService.OrderInfo orderInfo = ((SeppukuMap.SeppukuService.OrderInfo)(inValues[0]));
            return this.BeginaddOrder(orderInfo, callback, asyncState);
        }
        
        private object[] OnEndaddOrder(System.IAsyncResult result) {
            this.EndaddOrder(result);
            return null;
        }
        
        private void OnaddOrderCompleted(object state) {
            if ((this.addOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addOrderAsync(SeppukuMap.SeppukuService.OrderInfo orderInfo) {
            this.addOrderAsync(orderInfo, null);
        }
        
        public void addOrderAsync(SeppukuMap.SeppukuService.OrderInfo orderInfo, object userState) {
            if ((this.onBeginaddOrderDelegate == null)) {
                this.onBeginaddOrderDelegate = new BeginOperationDelegate(this.OnBeginaddOrder);
            }
            if ((this.onEndaddOrderDelegate == null)) {
                this.onEndaddOrderDelegate = new EndOperationDelegate(this.OnEndaddOrder);
            }
            if ((this.onaddOrderCompletedDelegate == null)) {
                this.onaddOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddOrderCompleted);
            }
            base.InvokeAsync(this.onBeginaddOrderDelegate, new object[] {
                        orderInfo}, this.onEndaddOrderDelegate, this.onaddOrderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SeppukuMap.SeppukuService.SeppukuServiceSoap.BeginremoveOrder(SeppukuMap.SeppukuService.removeOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginremoveOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginremoveOrder(SeppukuMap.SeppukuService.OrderInfo orderInfo, System.AsyncCallback callback, object asyncState) {
            SeppukuMap.SeppukuService.removeOrderRequest inValue = new SeppukuMap.SeppukuService.removeOrderRequest();
            inValue.Body = new SeppukuMap.SeppukuService.removeOrderRequestBody();
            inValue.Body.orderInfo = orderInfo;
            return ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).BeginremoveOrder(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeppukuMap.SeppukuService.removeOrderResponse SeppukuMap.SeppukuService.SeppukuServiceSoap.EndremoveOrder(System.IAsyncResult result) {
            return base.Channel.EndremoveOrder(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndremoveOrder(System.IAsyncResult result) {
            SeppukuMap.SeppukuService.removeOrderResponse retVal = ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).EndremoveOrder(result);
        }
        
        private System.IAsyncResult OnBeginremoveOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SeppukuMap.SeppukuService.OrderInfo orderInfo = ((SeppukuMap.SeppukuService.OrderInfo)(inValues[0]));
            return this.BeginremoveOrder(orderInfo, callback, asyncState);
        }
        
        private object[] OnEndremoveOrder(System.IAsyncResult result) {
            this.EndremoveOrder(result);
            return null;
        }
        
        private void OnremoveOrderCompleted(object state) {
            if ((this.removeOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.removeOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void removeOrderAsync(SeppukuMap.SeppukuService.OrderInfo orderInfo) {
            this.removeOrderAsync(orderInfo, null);
        }
        
        public void removeOrderAsync(SeppukuMap.SeppukuService.OrderInfo orderInfo, object userState) {
            if ((this.onBeginremoveOrderDelegate == null)) {
                this.onBeginremoveOrderDelegate = new BeginOperationDelegate(this.OnBeginremoveOrder);
            }
            if ((this.onEndremoveOrderDelegate == null)) {
                this.onEndremoveOrderDelegate = new EndOperationDelegate(this.OnEndremoveOrder);
            }
            if ((this.onremoveOrderCompletedDelegate == null)) {
                this.onremoveOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnremoveOrderCompleted);
            }
            base.InvokeAsync(this.onBeginremoveOrderDelegate, new object[] {
                        orderInfo}, this.onEndremoveOrderDelegate, this.onremoveOrderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SeppukuMap.SeppukuService.SeppukuServiceSoap.BeginGetMapModel(SeppukuMap.SeppukuService.GetMapModelRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMapModel(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetMapModel(System.AsyncCallback callback, object asyncState) {
            SeppukuMap.SeppukuService.GetMapModelRequest inValue = new SeppukuMap.SeppukuService.GetMapModelRequest();
            inValue.Body = new SeppukuMap.SeppukuService.GetMapModelRequestBody();
            return ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).BeginGetMapModel(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeppukuMap.SeppukuService.GetMapModelResponse SeppukuMap.SeppukuService.SeppukuServiceSoap.EndGetMapModel(System.IAsyncResult result) {
            return base.Channel.EndGetMapModel(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private SeppukuMap.SeppukuService.MapModel EndGetMapModel(System.IAsyncResult result) {
            SeppukuMap.SeppukuService.GetMapModelResponse retVal = ((SeppukuMap.SeppukuService.SeppukuServiceSoap)(this)).EndGetMapModel(result);
            return retVal.Body.GetMapModelResult;
        }
        
        private System.IAsyncResult OnBeginGetMapModel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetMapModel(callback, asyncState);
        }
        
        private object[] OnEndGetMapModel(System.IAsyncResult result) {
            SeppukuMap.SeppukuService.MapModel retVal = this.EndGetMapModel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMapModelCompleted(object state) {
            if ((this.GetMapModelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMapModelCompleted(this, new GetMapModelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMapModelAsync() {
            this.GetMapModelAsync(null);
        }
        
        public void GetMapModelAsync(object userState) {
            if ((this.onBeginGetMapModelDelegate == null)) {
                this.onBeginGetMapModelDelegate = new BeginOperationDelegate(this.OnBeginGetMapModel);
            }
            if ((this.onEndGetMapModelDelegate == null)) {
                this.onEndGetMapModelDelegate = new EndOperationDelegate(this.OnEndGetMapModel);
            }
            if ((this.onGetMapModelCompletedDelegate == null)) {
                this.onGetMapModelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMapModelCompleted);
            }
            base.InvokeAsync(this.onBeginGetMapModelDelegate, null, this.onEndGetMapModelDelegate, this.onGetMapModelCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SeppukuMap.SeppukuService.SeppukuServiceSoap CreateChannel() {
            return new SeppukuServiceSoapClientChannel(this);
        }
        
        private class SeppukuServiceSoapClientChannel : ChannelBase<SeppukuMap.SeppukuService.SeppukuServiceSoap>, SeppukuMap.SeppukuService.SeppukuServiceSoap {
            
            public SeppukuServiceSoapClientChannel(System.ServiceModel.ClientBase<SeppukuMap.SeppukuService.SeppukuServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetUsers(SeppukuMap.SeppukuService.GetUsersRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetUsers", _args, callback, asyncState);
                return _result;
            }
            
            public SeppukuMap.SeppukuService.GetUsersResponse EndGetUsers(System.IAsyncResult result) {
                object[] _args = new object[0];
                SeppukuMap.SeppukuService.GetUsersResponse _result = ((SeppukuMap.SeppukuService.GetUsersResponse)(base.EndInvoke("GetUsers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateGameState(SeppukuMap.SeppukuService.UpdateGameStateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateGameState", _args, callback, asyncState);
                return _result;
            }
            
            public SeppukuMap.SeppukuService.UpdateGameStateResponse EndUpdateGameState(System.IAsyncResult result) {
                object[] _args = new object[0];
                SeppukuMap.SeppukuService.UpdateGameStateResponse _result = ((SeppukuMap.SeppukuService.UpdateGameStateResponse)(base.EndInvoke("UpdateGameState", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginaddOrder(SeppukuMap.SeppukuService.addOrderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("addOrder", _args, callback, asyncState);
                return _result;
            }
            
            public SeppukuMap.SeppukuService.addOrderResponse EndaddOrder(System.IAsyncResult result) {
                object[] _args = new object[0];
                SeppukuMap.SeppukuService.addOrderResponse _result = ((SeppukuMap.SeppukuService.addOrderResponse)(base.EndInvoke("addOrder", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginremoveOrder(SeppukuMap.SeppukuService.removeOrderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("removeOrder", _args, callback, asyncState);
                return _result;
            }
            
            public SeppukuMap.SeppukuService.removeOrderResponse EndremoveOrder(System.IAsyncResult result) {
                object[] _args = new object[0];
                SeppukuMap.SeppukuService.removeOrderResponse _result = ((SeppukuMap.SeppukuService.removeOrderResponse)(base.EndInvoke("removeOrder", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMapModel(SeppukuMap.SeppukuService.GetMapModelRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMapModel", _args, callback, asyncState);
                return _result;
            }
            
            public SeppukuMap.SeppukuService.GetMapModelResponse EndGetMapModel(System.IAsyncResult result) {
                object[] _args = new object[0];
                SeppukuMap.SeppukuService.GetMapModelResponse _result = ((SeppukuMap.SeppukuService.GetMapModelResponse)(base.EndInvoke("GetMapModel", _args, result)));
                return _result;
            }
        }
    }
}
